service: serverless-cci-example
# app and org for use with dashboard.serverless.com
org: caranfimo
app: basic-service-nodejs
name: basic-service-nodejs
component: aws-lambda

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2

functions:
  index:
    handler: app.app
    events:
      - http:
          path: /
          method: get

  user:
    handler: app.app
    events:
      - http:
          path: /users
          method: get

