service: basic-service
# app and org for use with dashboard.serverless.com
org: caranfimo
app: basic-service-nodejs
name: basic-service-nodejs

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2

functions:
  index:
    handler: routes/index.router
    events:
      - http:
          path: /
          method: get

  user:
    handler: routes/users.router
    events:
      - http:
          path: /users
          method: get

