# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t bdb-basic-service-nodejs .
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: echo me
          command: echo "Hello"
      - run:
          name: Run Tests
          command: npm run test
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - node/install-packages
      - serverless/setup:
          provider: AWS
          app-name: serverless-framework-orb
          org-name: circleci
      - run:
          name: Local invoke add function
          command: serverless invoke local --function add --path 'sampleData/data.json'
      - run:
          command: serverless deploy -v
          name: deploy
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  serverless: circleci/serverless-framework@1.0.1
  aws-cli: circleci/aws-cli@0.1.22
  node: circleci/node@2.0

workflows:
  push_image:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: bdb-basic-service-nodejs-test
          tag: "$CIRCLE_SHA1"

