# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t bdb-basic-service-nodejs .
      - run: docker run bdb-basic-service-nodejs npm test
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: 871206902600.dkr.ecr.us-east-2.amazonaws.com
          aws-access-key-id: AKIA4VV72LNEBMMEA6VH
          aws-secret-access-key: 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
          create-repo: true
          dockerfile: .
          path: .
          region: us-east-2
          repo: bdb-basic-service-nodejs-test
          tag: "$CIRCLE_SHA1"
